channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.4
  - python=3.9.12
  - readline=8.1.2
  - setuptools=59.5.0 # https://github.com/pytorch/pytorch/issues/69894
  - sqlite=3.38.2
  - tk=8.6.11
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
      - --requirement requirements.txt
