seed_everything: 142
name: ali_textmatcher
trainer:
  max_epochs: 30
model:
  class_path: src.models.TextMatcher
  init_args:
    model_name_or_path: bert-base-chinese
    max_length: 256
    dropout: 0.1
    learning_rate: 2.0e-05
data:
  class_path: src.datamodules.AliDataModule
  init_args:
    cat: all
    columns:
      - title
    test_name: ""
    train_ratio: null
    test_ratio: null
    batch_size: 32
    num_workers: 0
    pin_memory: true
